catalog/urls.py
from django.urls import path
from .views import SupplementDetail, SupplementCreate, SupplementUpdate, supplement_import, supplement_list, ShopDetail

urlpatterns = [
    path('supplement/', supplement_list, name='supplement_list'),
    path('supplement/c', SupplementCreate.as_view(), name='supplement_create'),
    path('supplement/u/<slug:slug>', SupplementUpdate.as_view(), name='supplement_update'),
    path('supplement/d/<slug:slug>', SupplementDetail.as_view(), name='supplement_detail'),
    path('supplement/import', supplement_import, name='supplement_import'),
    path('shop/d/<int:pk>', ShopDetail.as_view(), name='shop_detail'),
]

herbs/urls.py
from django.contrib import admin
from django.urls import include, path
from catalog.views import account_profile

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('accounts/profile/', account_profile, name='account_profile'),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
from django.template.defaultfilters import slugify 
from django.contrib.auth.models import User


class Category(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=7)

    class Meta:
        verbose_name_plural = 'Categories'
        ordering = ['name']

    def __str__(self):
        return self.name

# Properties
class Tag(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Neurotransmitter(models.Model):
    name = models.CharField(max_length=50)
    color = models.CharField(max_length=7)

    def __str__(self):
        return self.name


class Producent(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class Shop(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop_detail', kwargs={'pk': self.pk})


class Supplement(models.Model):
    name = models.CharField(max_length=50, unique=True)
    polish_name = models.CharField(max_length=50, blank=True, null=True)
    users = models.ManyToManyField(User, related_name = 'user', blank=True)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, blank=True, null=True)
    tags = models.ManyToManyField(Tag, blank=True)
    neurotransmitters = models.ManyToManyField(Neurotransmitter, blank=True)
    description = models.TextField(blank=True, null=True)
    item_price = models.DecimalField(max_digits=6, decimal_places=2, blank=True, null=True)
    item_weight = models.DecimalField(max_digits=7, decimal_places=3, blank=True, null=True)
    portion_weight_min = models.DecimalField(max_digits=6, decimal_places=4, blank=True, null=True)
    portion_weight_max = models.DecimalField(max_digits=6, decimal_places=4, blank=True, null=True)
    daily_intakes_min = models.IntegerField(blank=True, null=True)
    daily_intakes_max = models.IntegerField(blank=True, null=True)
    meal_relation = models.CharField(max_length=1, choices=(('B', 'Before meal'), ('W', 'With meal'), ('A', 'After meal')), blank=True, null=True)
    country_of_origin = models.CharField(max_length=50, blank=True, null=True)
    date_of_discovery = models.DateField(blank=True, null=True)
    bioavailability = models.DecimalField(max_digits=3, decimal_places=2, blank=True, null=True)
    producent = models.ForeignKey(Producent, blank=True, null=True, on_delete=models.SET_NULL)
    shop = models.ForeignKey(Shop, blank=True, null=True, on_delete=models.SET_NULL)
    url = models.URLField(blank=True, null=True)
    slug = models.SlugField(max_length=40, blank=True, unique=True)

    @property
    def daily_cost_min(self):
        a = self.item_price and self.item_weight and self.portion_weight_min and self.daily_intakes_min
        if a:
            unit_price = self.item_price / self.item_weight
            daily_cost = unit_price * self.portion_weight_min * self.daily_intakes_min
            return round(daily_cost, 2)
        else:
            return 0

    @property
    def daily_cost_max(self):
        a = self.item_price and self.item_weight and self.portion_weight_max and self.daily_intakes_max
        if a:
            unit_price = self.item_price / self.item_weight
            daily_cost = unit_price * self.portion_weight_max * self.daily_intakes_max
            return round(daily_cost, 2)
        else:
            return 0

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('supplement_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']


class Visitor(models.Model):
    ip = models.GenericIPAddressField()
    timestamp = models.DateTimeField(auto_now_add=True)

catalog/forms.py
from django.forms import ModelForm, Form, FileField
from django.forms.widgets import TextInput
from .models import Supplement, Category, Neurotransmitter


class SupplementForm(ModelForm):
    
    class Meta:
        model = Supplement
        exclude = ('slug',)


class SupplementImportForm(Form):
    file = FileField(
        label='Select a file',
    )


class CategoryForm(ModelForm):
    
    class Meta:
        model = Category
        fields = '__all__'
        widgets = {
            'color': TextInput(attrs={'type': 'color'}),
        }


class NeurotransmitterForm(ModelForm):
    
    class Meta:
        model = Neurotransmitter
        fields = '__all__'
        widgets = {
            'color': TextInput(attrs={'type': 'color'}),
        }

catalog/views.py
from django.db.models import Sum
from django.shortcuts import render
from django.views.generic import DetailView, FormView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import Supplement, Shop, Visitor
from .forms import SupplementImportForm, SupplementForm

import csv
import io


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def supplement_list(request):
    c = {}
    ip = get_client_ip(request)
    v = Visitor.objects.create(ip=ip)
    c['supplements'] = Supplement.objects.all()
    if request.user.is_authenticated:
        if request.method == 'GET':
            if request.GET.get('q'):
                order = request.GET.get('q')
                if order == 'daily_cost_min':
                    c['supplements'] = sorted(Supplement.objects.all(), key=lambda t: t.daily_cost_min)
                elif order == 'daily_cost_max':
                    c['supplements'] = sorted(Supplement.objects.all(), key=lambda t: t.daily_cost_max)
                else:
                    c['supplements'] = Supplement.objects.order_by(f'-{order}', 'name')
            if request.GET.get('search'):
                search_string = request.GET.get('search')
                c['supplements'] = Supplement.objects.filter(name__icontains=search_string)
            return render(request, 'catalog/supplement_list_form.html', c)
        if request.method == 'POST':
            pks = list(request.POST.keys())[1:]
            pks = list(map(int, pks))
            supplements = Supplement.objects.filter(pk__in=pks)
            user = request.user
            for supplement in supplements:
                supplement.users.add(user)
                supplement.save()
            for supplement in Supplement.objects.all():
                if supplement not in supplements:
                    supplement.users.remove(user)
            cost_min = sum(s.daily_cost_min for s in supplements)
            cost_max = sum(s.daily_cost_max for s in supplements)
            item_cost = sum(s.item_price for s in supplements)
            request.session['daily_cost_min_sum'] = str(cost_min)
            request.session['daily_cost_max_sum'] = str(cost_max)
            request.session['monthly_cost_min_sum'] = str(cost_min*31)
            request.session['monthly_cost_max_sum'] = str(cost_max*31)
            request.session['item_cost'] = str(item_cost)
            return render(request, 'catalog/supplement_list_form.html', c)
    return render(request, 'catalog/supplement_list.html', c)


class SupplementDetail(DetailView):
    model = Supplement
    context_object_name = 'supplement'


class SupplementCreate(UserPassesTestMixin, CreateView):
    form_class = SupplementForm
    template_name = 'catalog/supplement_create.html'

    def test_func(self):
        return self.request.user.is_staff


class SupplementUpdate(UserPassesTestMixin, UpdateView):
    model = Supplement
    form_class = SupplementForm
    template_name = 'catalog/supplement_create.html'

    def test_func(self):
        return self.request.user.is_staff


class ShopDetail(DetailView):
    model = Shop
    context_object_name = 'shop'


def supplement_import(request):
    if request.method == 'POST':
        form = SupplementImportForm(request.POST, request.FILES)
        if form.is_valid():
            decoded_file = form.cleaned_data['file'].read().decode('utf-8')
            file = io.StringIO(decoded_file)
            imported = list()
            rejected = list()
            for row in csv.DictReader(file, delimiter=','):
                try:
                    obj = Supplement(**row)
                    obj.save()
                    imported.append(obj)
                except:
                    rejected.append(row)
                    
            return render(request, 'catalog/supplement_import.html', {'imported': imported, 'rejected': rejected})
    else:
        form = SupplementImportForm()
    return render(request, 'catalog/supplement_import.html', {'form': form})


@login_required
def account_profile(request):
    user = request.user
    user_supplements = Supplement.objects.filter(users=user).order_by('category')
    return render(request, 'registration/account_profile.html', {'user_supplements': user_supplements})

catalog/templates/catalog/shop_detail.html
{% extends 'index.html' %}

{% load catalog_extras %}

{% block content %}

<h1 class="title">
	{{ shop.name }}
</h1>

{% for supplement in shop.supplement_set.all %}
<div>
    <p>
        <span class="tag is-black" style="background-color:{{ supplement.category.color }};">
        {{ supplement.name }}</span>
    </p>
</div>
{% endfor %}

{% endblock content %}

catalog/templates/catalog/supplement_create.html
{% extends 'index.html' %}

{% load widget_tweaks %}

{% block content %}

<h1 class="title">
	Dodaj suplement
</h1>

<div class="columns is-centered">
	<form class="column is-full-mobile is-half-tablet" method="post" novalidate>
		{% csrf_token %}
		{% for hidden_field in form.hidden_fields %}
		{{ hidden_field }}
		{% endfor %}

		{% for error in form.non_field_errors %}
		<p class="help is-danger">{{ error }}</p>
		{% endfor %}

		{% for field in form.visible_fields %}


		{% if field.name == 'tags' or field.name == 'neurotransmitters' %}
		<div class="field">
			<div class="select is-multiple" style="width:100%">
				<label class="label">{{ field.label_tag }}</label>
				{% for error in field.errors %}
				<p class="help is-danger">{{ error }}</p>
	            {% endfor %}
            	<div class="control">
				{% render_field field class='input is-success' %}
				</div>
			</div>
		</div>
		{% elif field.name == 'description' %}
		<div class="field">
			<label class="label">{{ field.label_tag }}</label>
			{% for error in field.errors %}
			<p class="help is-danger">{{ error }}</p>
            {% endfor %}
            <div class="control">
			{% render_field field class='textarea is-success' rows='5' %}
			</div>
		</div>
		{% else %}
		<div class="field">
            <label class="label">{{ field.label_tag }}</label>
            
			{% for error in field.errors %}
			<p class="help is-danger">{{ error }}</p>
            {% endfor %}
            
			<div class="control">
				{% render_field field class='input is-success' %}
            </div>
            
			{% if field.help_text %}
			<p class="help">{{ field.help_text }}</p>
			{% endif %}
		</div>
		{% endif %}
        {% endfor %}

        <div class="field is-grouped submit-buttons">
			<div class="control">
				<button type="submit" class="button is-link">Zapisz</button>
			</div>
			<div class="control">
				<a type="button" class="button is-link is-light" href="{% url 'supplement_list' %}">Anuluj</a>
			</div>
		</div>

	</form>
</div>

{% endblock %}

catalog/templates/catalog/supplement_detail.html
{% extends 'index.html' %}

{% load catalog_extras %}

{% block content %}

<h1 class="title">
	{{ supplement.name }}
</h1>

{% if request.user.is_authenticated and request.user.is_staff %}
<div class="field is-grouped submit-buttons">
    <div class="control">
        <a type="button" class="button is-link is-light" href="{% url 'supplement_update' object.slug %}">Update</a>
    </div>
</div>
{% endif %}

{% if supplement.category %}
    <div>
        <p>
            <span>Category: </span>
            <span class="tag is-black" style="background-color:{{ supplement.category.color }};">{{ supplement.category.name }}</span>
        </p>
    </div><br>
{% endif %}

<div>
    <p>
        <span>Tags: </span>
        {% for tag in supplement.tags.all %}
        <span class="tag" >{{ tag.name }}</span>
        {% endfor %}
    </p>
</div><br>

<div>
    <p>
        <span>Neurotransmitters: </span>
        {% for n in supplement.neurotransmitters.all %}
        <span class="tag is-black" style="background-color:{{ n.color }};">{{ n.name }}</span>
        {% endfor %}
    </p>
</div><br>

{% if supplement.item_price %}
<div>
    <span>Item price: </span>
    <span>{{ supplement.item_price }} zł</span>
</div>
{% endif %}

{% if supplement.item_weight %}
<div>
    <span>Item weight: </span>
    <span>{{ supplement.item_weight|floatformat:2 }} g</span>
</div>
{% endif %}

{% if supplement.portion_weight_min %}
<div>
    <span>Portion weight min: </span>
    <span>{{ supplement.portion_weight_min|multiply:1000|floatformat }} mg</span>
</div>
{% endif %}

{% if supplement.portion_weight_max %}
<div>
    <span>Portion weight max: </span>
    <span>{{ supplement.portion_weight_max|multiply:1000|floatformat }} mg</span>
</div>
{% endif %}

{% if supplement.daily_cost_min %}
<div>
    <span>Daily cost min: </span>
    <span>{{ supplement.daily_cost_min }} zł</span>
</div>
{% endif %}

{% if supplement.daily_cost_max %}
<div>
    <span>Daily cost max: </span>
    <span>{{ supplement.daily_cost_max }} zł</span>
</div>
{% endif %}

{% if supplement.daily_intakes_min %}
<div>
    <span>Daily intakes min: </span>
    <span>{{ supplement.daily_intakes_min }}</span>
</div>
{% endif %}

{% if supplement.daily_intakes_max %}
<div>
    <span>Daily intakes max: </span>
    <span>{{ supplement.daily_intakes_max }}</span>
</div>
{% endif %}

{% if supplement.meal_relation %}
<div>
    <span>Meal relation: </span>
    <span>{{ supplement.meal_relation }}</span>
</div>
{% endif %}

{% if supplement.country_of_origin %}
<div>
    <span>Country of origin: </span>
    <span>{{ supplement.country_of_origin }}</span>
</div>
{% endif %}

{% if supplement.date_of_discovery %}
<div>
    <span>Date of discovery: </span>
    <span>{{ supplement.date_of_discovery }}</span>
</div>
{% endif %}

{% if supplement.bioavailability %}
<div>
    <span>Bioavailability: </span>
    <span>{{ supplement.bioavailability }}</span>
</div>
{% endif %}

<div class="text">{{ supplement.description }}</div>

{% endblock content %}

catalog/templates/catalog/supplement_import.html
{% extends 'index.html' %}

{% load widget_tweaks %}

{% block content %}

	{% if form %}
	<form method="post" enctype="multipart/form-data">
		<div class="buttons has-addons">
		{% csrf_token %}
		{% for field in form.visible_fields %}
		{{ field.errors }}
		<div class="file has-name">
			{% render_field field class="" %}
			<button class="button is-primary" type="submit">Upload</button>
		</div>
		{% endfor %}	
		
		</div>
	</form>
	{% endif %}

	{% if imported %}
		{% for e in imported %}
			<p>{{ e.name }}</p>
		{% endfor %}
	{% endif %}

	{% if rejected %}
		{% for r in rejected %}
			<p class="has-text-danger">{{ r.name }}</p>
		{% endfor %}
	{% endif %}

	<div><a href="{% url 'supplement_list' %}">Return to home</a></div>

{% endblock %}

catalog/templates/catalog/supplement_list.html
{% extends 'index.html' %}

{% block content %}

<h1 class="title">
	Supplements
</h1>
<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
  <thead>
    <tr>
      <th><a href="?q=name">Name</a></th>
      <th><a href="?q=polish_name">Polish name</a></th>
      <th><a href="?q=category">Category</a></th>
      <th><a href="?q=item_price">Price</a></th>
      <th><a href="?q=daily_cost_min">Min. daily $</a></th>
      <th><a href="?q=daily_cost_max">Max. daily $</a></th>
      <th><a href="?q=shop">Shop</a></th>
      <th><a href="?q=url">Url</a></th>
      {% if request.user.is_authenticated and request.user.is_staff %}
      <th></th>
      {% endif %}
    </tr>
  </thead>
  <tbody>

    <form method="post" action="{% url 'supplement_list' %}">
    {% csrf_token %}

    <div class="field">
      <div class="control">
          <input class="button is-link is-light" type="submit" value="Get cost">
      </div>
    </div>
    
    {% for supplement in supplements %}
    <tr>
      <td>
        <a href="{% url 'supplement_detail' slug=supplement.slug %}">{{ supplement.name }}</a>
      </td>
      <td>
        {% if supplement.polish_name %}
          <a href="{% url 'supplement_detail' slug=supplement.slug %}">{{ supplement.polish_name }}</a>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.category %}
          <span class="tag is-black" style="background-color:{{ supplement.category.color }};">
            {{ supplement.category.name }}
          </span>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}   
      </td>
      <td>
        {% if supplement.item_price %}
          {{ supplement.item_price }}
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.daily_cost_min %}
          {{ supplement.daily_cost_min }}
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.daily_cost_max %}
          {{ supplement.daily_cost_max }}
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.shop %}
        <a href="{% url 'shop_detail' supplement.shop.pk %}">{{ supplement.shop.name }}</a>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.url %}
        <a href="{{ supplement.url }}" target="_blank">Link</a>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      {% if request.user.is_authenticated and request.user.is_staff %}
      <td>
        <div class="field is-grouped submit-buttons">
          <div class="control">
            <a type="button" class="button is-link is-light is-small" href="{% url 'supplement_update' supplement.slug %}">U</a>
          </div>
        </div>
      </td>
      {% endif %}
    </tr>
    {% endfor %}

    </form>

  </tbody>
</table>

{% endblock content %}

catalog/templates/catalog/supplement_list_form.html
{% extends 'index.html' %}

{% block content %}

<h1 class="title">
	Supplements
</h1>

{% if request.session.item_cost %}
  <p>Daily min cost: {{ request.session.daily_cost_min_sum }} zł</p>
  <p>Daily max cost: {{ request.session.daily_cost_max_sum }} zł</p>
  <p>Monthly min cost: {{ request.session.monthly_cost_min_sum }} zł</p>
  <p>Monthly max cost: {{ request.session.monthly_cost_max_sum }} zł</p>
  <p>Items cost: {{ request.session.item_cost }} zł</p>
{% endif %}

<div class="columns">
  <div class="column is-right">
    <form method="get">
      <div class="field is-grouped is-horizontal">
        <div class="control">
          <input class="input is-primary" type="search" name="search" value="{{ request.GET.search }}" placeholder="Search"/>
        </div>
        <div class="control">
          <input class="button is-link is-light" type="submit" value="Search"/>
        </div>
        <div class="control">
          <a class="button is-link is-light" href="{% url 'supplement_list' %}">Reset</a>
        </div>
      </div>
    </form>
  </div>
</div>


<table class="table is-bordered is-striped is-narrow is-hoverable is-fullwidth">
	<thead>
    <tr>
      <th></th>
      <th><a href="?q=name">Name</a></th>
      <th><a href="?q=polish_name">Polish name</a></th>
      <th><a href="?q=category">Category</a></th>
      <th><a href="?q=item_price">Price</a></th>
      <th><a href="?q=daily_cost_min">Min. daily $</a></th>
      <th><a href="?q=daily_cost_max">Max. daily $</a></th>
      <th><a href="?q=shop">Shop</a></th>
      <th><a href="?q=url">Url</a></th>
      {% if request.user.is_authenticated and request.user.is_staff %}
      <th></th>
      {% endif %}
    </tr>
  </thead>
  <tbody>

    <form method="post" action="{% url 'supplement_list' %}">
    {% csrf_token %}

    <div class="field">
      <div class="control">
          <input class="button is-link is-light" type="submit" value="Get cost">
      </div>
    </div>
    
    {% for supplement in supplements %}
    <tr>
      <td>
        {% if request.user in supplement.users.all %}
          <input type="checkbox" name="{{ supplement.pk }}" id="{{ supplement.pk }}" checked>
        {% else %}
          <input type="checkbox" name="{{ supplement.pk }}" id="{{ supplement.pk }}">
        {% endif %}
      </td>
      <td>
        <a href="{% url 'supplement_detail' slug=supplement.slug %}">{{ supplement.name }}</a>
      </td>
      <td>
        {% if supplement.polish_name %}
          <a href="{% url 'supplement_detail' slug=supplement.slug %}">{{ supplement.polish_name }}</a>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.category %}
          <span class="tag is-black" style="background-color:{{ supplement.category.color }};">
            {{ supplement.category.name }}
          </span>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}   
      </td>
      <td>
        {% if supplement.item_price %}
          {{ supplement.item_price }}
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.daily_cost_min %}
          {{ supplement.daily_cost_min }}
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.daily_cost_max %}
          {{ supplement.daily_cost_max }}
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.shop %}
        <a href="{% url 'shop_detail' supplement.shop.pk %}">{{ supplement.shop.name }}</a>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      <td>
        {% if supplement.url %}
        <a href="{{ supplement.url }}" target="_blank">Link</a>
        {% else %}
          <span class="is-italic has-text-weight-light">Unknown</span>
        {% endif %}
      </td>
      {% if request.user.is_authenticated and request.user.is_staff %}
      <td>
        <div class="field is-grouped submit-buttons">
          <div class="control">
            <a type="button" class="button is-link is-light is-small" href="{% url 'supplement_update' supplement.slug %}">U</a>
          </div>
        </div>
      </td>
      {% endif %}
    </tr>
    {% endfor %}

    </form>

  </tbody>
</table>

{% endblock content %}